"""Education application-owned persistence interfaces."""

from typing import Protocol
from uuid import UUID

from app.education.domain.models import Course, EducationalEnvironment, LearningUnit, Section


class EnvironmentRepository(Protocol):
    def add(self, environment: EducationalEnvironment) -> EducationalEnvironment: ...
    def get_by_teacher_space(self, teacher_space_id: UUID) -> EducationalEnvironment | None: ...
    def update(self, environment: EducationalEnvironment) -> EducationalEnvironment: ...


class CourseRepository(Protocol):
    def add(self, course: Course) -> Course: ...
    def list_by_environment(self, environment_id: UUID) -> list[Course]: ...
    def get_in_environment(self, course_id: UUID, environment_id: UUID) -> Course | None: ...
    def update(self, course: Course) -> Course: ...


class SectionRepository(Protocol):
    def add(self, section: Section) -> Section: ...
    def list_by_course(self, course_id: UUID) -> list[Section]: ...
    def get_in_course(self, section_id: UUID, course_id: UUID) -> Section | None: ...
    def update(self, section: Section) -> Section: ...
    def delete(self, section: Section) -> None: ...


class LearningUnitRepository(Protocol):
    def add(self, unit: LearningUnit) -> LearningUnit: ...
    def list_by_section(self, section_id: UUID) -> list[LearningUnit]: ...
    def get_in_section(self, unit_id: UUID, section_id: UUID) -> LearningUnit | None: ...
    def update(self, unit: LearningUnit) -> LearningUnit: ...
    def delete(self, unit: LearningUnit) -> None: ...
