"""Education application-owned persistence interfaces."""

from typing import Protocol
from uuid import UUID

from app.education.domain.models import Course, EducationalEnvironment


class EnvironmentRepository(Protocol):
    def add(self, environment: EducationalEnvironment) -> EducationalEnvironment: ...
    def get_by_teacher_space(self, teacher_space_id: UUID) -> EducationalEnvironment | None: ...
    def update(self, environment: EducationalEnvironment) -> EducationalEnvironment: ...


class CourseRepository(Protocol):
    def add(self, course: Course) -> Course: ...
    def list_by_environment(self, environment_id: UUID) -> list[Course]: ...
    def get_in_environment(self, course_id: UUID, environment_id: UUID) -> Course | None: ...
    def update(self, course: Course) -> Course: ...
