"""Interfaces owned by the identity application layer."""

from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.identity.domain.models import Identity


class IdentityRepository(Protocol):
    def get_by_email(self, email: str) -> Identity | None: ...
    def get_by_id(self, identity_id: UUID) -> Identity | None: ...
    def add(self, identity: Identity) -> Identity: ...


class PasswordService(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...


class SessionRepository(Protocol):
    def create(self, identity_id: UUID, token_digest: str, expires_at: datetime) -> None: ...
    def get_identity_id(self, token_digest: str, now: datetime) -> UUID | None: ...
    def revoke(self, token_digest: str, now: datetime) -> bool: ...
