from typing import Protocol
from uuid import UUID

from app.content.domain.models import Content


class ContentRepository(Protocol):
    def add(self, content: Content) -> Content: ...
    def list_owned(self, owner_user_id: UUID) -> list[Content]: ...
    def get_by_id(self, content_id: UUID) -> Content | None: ...
    def get_owned(self, content_id: UUID, owner_user_id: UUID) -> Content | None: ...
    def update(self, content: Content) -> Content: ...
    def delete(self, content: Content) -> None: ...
