from typing import Protocol
from uuid import UUID

from app.assessment.domain.models import AssessmentDefinition


class AssessmentDefinitionRepository(Protocol):
    def add(self, definition: AssessmentDefinition) -> AssessmentDefinition: ...
    def get(self, definition_id: UUID, activity_id: UUID) -> AssessmentDefinition | None: ...
    def get_by_activity(self, activity_id: UUID) -> AssessmentDefinition | None: ...
    def update(self, definition: AssessmentDefinition) -> AssessmentDefinition: ...


from app.assessment.domain.attempts import AssessmentAttempt


class AssessmentAttemptRepository(Protocol):
    def add(self, attempt: AssessmentAttempt) -> AssessmentAttempt: ...
    def get_owned(
        self, attempt_id: UUID, definition_id: UUID, student_id: UUID
    ) -> AssessmentAttempt | None: ...
    def update(self, attempt: AssessmentAttempt) -> AssessmentAttempt: ...
    def list_owned(self, definition_id: UUID, student_id: UUID) -> list[AssessmentAttempt]: ...
