from typing import Protocol
from uuid import UUID

from app.assessment.domain.models import AssessmentDefinition


class AssessmentDefinitionRepository(Protocol):
    def add(self, definition: AssessmentDefinition) -> AssessmentDefinition: ...
    def get(self, definition_id: UUID, activity_id: UUID) -> AssessmentDefinition | None: ...
    def get_by_activity(self, activity_id: UUID) -> AssessmentDefinition | None: ...
    def update(self, definition: AssessmentDefinition) -> AssessmentDefinition: ...
