from typing import Protocol
from uuid import UUID

from app.assessment.domain.attempts import AssessmentAttempt, AssessmentAttemptStatus
from app.assessment.domain.models import AssessmentDefinition
from app.assessment.domain.results import AssessmentResult


class AssessmentDefinitionRepository(Protocol):
    def add(self, definition: AssessmentDefinition) -> AssessmentDefinition: ...
    def get(self, definition_id: UUID, activity_id: UUID) -> AssessmentDefinition | None: ...
    def get_by_id(self, definition_id: UUID) -> AssessmentDefinition | None: ...
    def get_by_activity(self, activity_id: UUID) -> AssessmentDefinition | None: ...
    def update(self, definition: AssessmentDefinition) -> AssessmentDefinition: ...


class AssessmentAttemptRepository(Protocol):
    def add(self, attempt: AssessmentAttempt) -> AssessmentAttempt: ...
    def get(
        self, attempt_id: UUID, definition_id: UUID
    ) -> AssessmentAttempt | None: ...
    def get_owned(
        self, attempt_id: UUID, definition_id: UUID, student_id: UUID
    ) -> AssessmentAttempt | None: ...
    def get_owned_by_id(
        self, attempt_id: UUID, student_id: UUID
    ) -> AssessmentAttempt | None: ...
    def update(self, attempt: AssessmentAttempt) -> AssessmentAttempt: ...
    def list_owned(self, definition_id: UUID, student_id: UUID) -> list[AssessmentAttempt]: ...
    def list_by_definition(
        self,
        definition_id: UUID,
        *,
        status: AssessmentAttemptStatus | None,
        offset: int,
        limit: int,
    ) -> list[AssessmentAttempt]: ...


class AssessmentResultRepository(Protocol):
    def add(self, result: AssessmentResult) -> AssessmentResult: ...
    def get(self, result_id: UUID, attempt_id: UUID) -> AssessmentResult | None: ...
    def get_by_attempt(self, attempt_id: UUID) -> AssessmentResult | None: ...
    def update(self, result: AssessmentResult) -> AssessmentResult: ...
